version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - cuisine-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://server:3001
    networks:
      - cuisine-network
    depends_on:
      server:
        condition: service_started

networks:
  cuisine-network:
    driver: bridge
